### ISSUE TITLE
Comment: Mutex Usage

### ISSUE THREAD

**Issue by ForgeMistress** [bloomen/transwarp#14]
See the following (on phone, formatting will be jacked up).

void shutdown() {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            done_ = true;
        }
        cond_var_.notify_all();
        for (std::thread& thread : threads_) {
            thread.join();
        }
        threads_.clear();
    }

Setting a boolean is an atomic operation, even without std::atomic to my knowledge, that doesn't require a lock. I recommend taking a look at the rest of your code and seeing where you can remove unneeded locks.

**Comment by bloomen** [comment]
Have a look at this: https://stackoverflow.com/a/9201088/2064089
Without synchronization of some form the compiler is not required to keep the boolean in sync across thread boundaries. We have to use either atomic or mutex here. Since we already require a mutex to protect the queue of functors it makes sense to use the same mutex to protect `done_` as well.

The only place in transwarp where `std::mutex` is used is the thread pool.

There are some other places that require locks but those use spin locks to prevent inversion of priority.
