### ISSUE TITLE
Schedule the same graph again

### ISSUE THREAD

**Issue by sdebionne** [bloomen/transwarp#17]
The documentation explicitly states that

> It is currently not possible to schedule the same graph again while it is still running

then suggests a solution with graph_pool.

The developers at Adobe's stlab in their [Concurrency](http://stlab.cc/libraries/concurrency/) library, a library that have a lot in common with transwarp, have worked on an upgrade of the `std::future` to fix some of their shortcoming that impact this project (continuation, cancellable). Maybe is is worth a look and provide a way to parametrize the future implementation in `transwarp`?

They also provide `Channels` with one can build graphs that can be used for multiple invocations and this may be a better alternative to graph_pool. Just a heads up and thanks for transwarp!

**Comment by bloomen** [comment]
Thank you for your feedback! Just to be clear though, the problem that `graph_pool` is trying to solve is not scheduling the same graph again but rather scheduling that graph again _while_ the graph is running. I'd be very interested in learning as to how other libraries solve this problem. What I am thinking to do now is to actually hide the graph pool concept inside the task class so that a task is essentially cloned automatically if `schedule` is called while the task is running.
