### ISSUE TITLE
`listener` and `executor` use `itask`

### ISSUE THREAD

**Issue by bloomen** [bloomen/transwarp#19]
Currently, the `listener` and `executor` interfaces refer to a shared_ptr of `node`. This should be changed to a shared_ptr of `itask` for greater flexibility.

**Comment by ebatz** [comment]
Could you take a look at https://github.com/ebatz/transwarp/commit/31116cd8d1bcb0d5237eb53d35ddd7f453ea725f and let me know what you think?

Passing around raw pointers, because `handle_event()` shouldn't modify or store the task object passed in anyway, and it's certainly guaranteed to continue to live while events are being handled.

**Comment by bloomen** [comment]
Cool, I just left the comments I had. Otherwise looks good!

**Comment by ebatz** [comment]
Thanks for the comments!
I have now done the same for the executor, and if you're happy I think we're good to go here.

**Comment by bloomen** [comment]
Just a small thing I commented on in the tests, otherwise good to go!
